name: "[CD] Continuous Delivery"

# Whenever a PR or a commit to main branch
# on:
#   push:
#     branches: [main]
on:
  pull_request:
    types: [opened, synchronize]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_steps]
      - uses: actions/checkout@v3
      ## ===========
      - name: "Debug"
        run: |
          ls -la
      - name: "Install dependencies"
        run: "npm install"
      - name: "Deploy"
        run: "npx vercel --prod"
