name: "[CI] Continuous Integration"

# Whenever a PR is created, or a commit is pushed
on:
  pull_request: 
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_steps]
      - uses: actions/checkout@v3
      ## ===========
      - name: "Debug"
        run: |
          ls -la
          echo "Second command of Debug"
      - name: "Install dependencies"
        run: "npm ci"
      - name: "Lint"
        run: "npm run lint"
  test:
    runs-on: ubuntu-latest
    container: cypress/browsers:node18.12.0-chrome107
    steps:
      ## [Common_CI_steps]
      - uses: actions/checkout@v3
      ## ===========
      - name: "Install dependencies"
        run: "npm install"
      - name: "test"
        run: "npm run test"
