name: "[CI] Continuous Integration"

# Whenever a PR is created, or a commit is pushed
on:
  pull_request: 
    types: [opened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      ## [Common_CI_steps]
      - uses: actions/checkout@v3
      ## ===========
      - name: "Debug"
        run: "ls -la"
      - name: "Lint"
        run: "npm run lint"
